name: Run experiment

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: read

    steps:
      - uses: artyom/test-multiline@main
        with:
          one: Value for argument one
          two: |
            line 1
            line 2
            line 3
          three: |
            key1=value 1
            key2=value 2
            key3=value three
