name: Build and publish docker image

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency: publish

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: |
            linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:latest
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=6,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
